url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Xavier Rosee
email: xavier@offtheground.io
description: "Xavier Rosée is a Video Game Marketing professional that provides Strategy and Branding consultancy, along with User Acquisition services for PC and Mobile Games. My range of services cater to everyone from AAA studios to solo indie developers."


# Team names, titles and social links
people:
- name: Xavier Rosée
  pic: 1
  position: Founder and Marketing Consultant
  social:
    - title: linkedin
      url: http://linkedin.com/in/xavierosee
    - title: twitter
      url: https://twitter.com/xavierosee


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
# address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
